version: '3'

services:
  web:
    build:
      context: .
      dockerfile: infrastructure/web/Dockerfile
    image: bkuhl/laravel-starter:web
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./infrastructure/web:/etc/nginx/conf.d
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_database
      MYSQL_USER: user
      MYSQL_PASSWORD: secret